import express from 'express';
import helmet from 'helmet';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { corsMiddleware } from './config/cors.js';
import { apiRateLimit } from './middleware/rate-limit.middleware.js';
import { errorHandler, notFound } from './middleware/error.middleware.js';
import { sendSuccess } from './utils/api-response.js';
import { authRoutes } from './routes/auth.routes.js';
import { userRoutes } from './routes/user.routes.js';
import { propertyRoutes } from './routes/property.routes.js';
import { favoriteRoutes } from './routes/favorite.routes.js';
import { ownerRoutes } from './routes/owner.routes.js';
import { adminRoutes } from './routes/admin.routes.js';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
export const app = express();
app.disable('x-powered-by');
app.use(helmet());
app.use(corsMiddleware);
app.use(express.json({ limit: '1mb' }));
app.use('/api', apiRateLimit);
app.get('/api/health', (_request, response) => sendSuccess(response, 200, { status: 'ok' }));
app.use('/api/auth', authRoutes);
app.use('/api/users', userRoutes);
app.use('/api/properties', propertyRoutes);
app.use('/api/favorites', favoriteRoutes);
app.use('/api/owner', ownerRoutes);
app.use('/api/admin', adminRoutes);
app.use(express.static(path.join(rootDir, 'frontend')));
app.use(notFound);
app.use(errorHandler);